### PR TITLE
Rename boilerplate readme file

### PR DESCRIPTION
**Pull request by kornelski**
Makes GitHub display it by default

### CODE REVIEW

**Comment by dpc** [comment]
I wasn't aware this function was ever added!

**Comment by dpc** [comment]
Oh dear. I haven't noticed, but I actually did not want `README_USING_THIS_REPO.md` to be `README.md`. Please let me know what you think about it, but the idea was that `README.md` should be personalized, and `cargo crev edit readme` would make the owner put some info about themselves, how they do review, what do they typically review.

The  `README_USING_THIS_REPO.md` was supposed to be a secondary thing...


Maybe we could compromise here and keep this, but modify `README.md` to have a section for personalized info from the owner, followed by the default section.

**Comment by kornelski** [comment]
What's the purpose of `cargo crev edit readme`?

My assumption was that the repo is for machine consumption, so the default readme is there only to explain to it to lost users who stumble upon it.

**Comment by dpc** [comment]
@kornelski Primary purpose is for machines to fetch from. But people will see this link, share it, etc, so it wouldn't hurt if the `README.md` was actually helpful for the humans. Machines don't care about it anyway.

**Comment by kornelski** [comment]
How about creating the default readme like this, once. Then don't overwrite it. Let users change it if they want to.

**Comment by dpc** [comment]
Yes. I'm hacking on it right now. But what if the user comes with a default README.md generated by github? I guess I'll just put a marker there and not overwrite if it is there.

**Comment by kornelski** [comment]
The easiest would be not to touch README if it exists already

**Comment by dpc** [comment]
@kornelski Then we're going to be often stuck with the default one created by github, which isn't very helpful. And now the secondary `README_USING_THIS_REPO.md` won't even be created.

**Pull request merged**
