### PR TITLE
Replace room ID with #crev

### PR DESCRIPTION
**Pull request by ShadowJonathan**
Checklist:

* [-] `cargo +nightly fmt --all`
* [-] Modify `CHANGELOG.md` if applicable

This is useful for when room IDs change (due to upgrades or else), and the readmes still point to a room ID instead of an alias.

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
Also, isn't the gitter chat dead?

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
> Also, isn't the gitter chat dead?

Matrix and Gitter merged or something, and now old gitter chats show up as different rooms under some different names or something, and bridges are not neccessary(?).

**Comment by ShadowJonathan** [comment]
gitter.im started migrating to matrix, the room would've been accessible under `#crev-dev_cargo-crev:gitter.im`, but it was removed appearantly?

**Comment by dpc** [comment]
Maybe I removed it myself, thinking that it will not be necessary anymore. I can't actually remember.

**Pull request merged**
