### PR TITLE
Add new crev logo.

### PR DESCRIPTION
**Pull request by ffranr**
Last Sunday, I had a go at making a logo for crev. What do you guys think?

I don't do this professionally, and I have thick skin, so please feel free to give honest feedback. It was fun to make regardless of whether you guys want to use it or not.

I've tried to capture the idea of dependencies coupling together such as to form a protective shield.

I took the README centering setup from here: https://github.com/meilisearch/MeiliSearch

Light rendering on my computer:
image

Dark rendering on my computer:
image

### CODE REVIEW

**Comment by dpc** [comment]
Woohoo. Better than the current one, that's for sure. :)

For `slog` I've paid someone like $20 on Fiverr or somewhere to make me a logo like I specified. I'm not afraid of doing it again. I think the main question is the idea behind the logo - what is each thing symbolizing, why is this and not other way etc. Then it's worth considering things like - how does it look in different sizes, is it distinct and recognizable etc.

I'll let this sit for a while and let other people comment. :) . Big :+1: for taking a stab at it.

**Comment by dbrgn** [comment]
Cool! So far I only have some bikeshedding to offer:

I like the "interleaved dependencies" concept, but it doesn't express the review part. It doesn't have to though, putting the concept of "review" in a logo is hard. Sometimes something simple good-looking is better than something that expresses many ideas but is too complex.

I'm also not a big fan of the transparent gradient. If you put a gradient in there, I'd keep it white.

Generally it doesn't look bad though!

PS: "varafiable" in the screenshots should be "verifiable" and "dependancy" should be "dependency" :slightly_smiling_face:

**Comment by dpc** [comment]
I like that there are two colors from two sides "digging into the inside". It a nice symbol of coming together, and reaching deep. 

I'm also not a big fan of the gradient. I'd make the background just white or transparent.

**Comment by ffranr** [comment]
@dpc @dbrgn Thank you both for your thoughtful comments! I also had doubts about the gradient background. Too many flashbacks of WordArt.

@dbrgn Thank you for correcting my spelling, it's not my forte!

I've just forced pushed a new version. This version has a transparent background. It's definitely cleaner (especially the dark rendering). I would be happy to hear any thoughts you guys may have on these versions.

Light rendering:
image

Dark rendering:
image

**Comment by chrysn** [comment]
I'm with dbrgn on the "would be nice to capture the review process" point -- but the interleaved inputs that make part of the shield capture the collaborative aspect well, and adding more would take away from the simplicity.

The blue gets lost in the dark version on my screen. Maybe this can be fixed by giving the whole shield a white background.

**Comment by ffranr** [comment]
@dpc I didn't realse this sort of thing was so easy to outsource! I'll checkout Fiverr.

@dbrgn @chrysn I agree that it would be nice to capture the review part. But I don't have any good ideas around that right now. Code review symbols usually seem to involve magnifying glasses, a bit like this: https://images.app.goo.gl/3JqaohsLSvjBuk8G8
I'm not sure how to combine that with the idea of security, and dependencies or packages.

Here's the logo again but with a light gray background and some text (dark rendering would be the same because there isn't any transparency):

image

**Comment by dpc** [comment]
I was actually thinking that the solid background would just the back of the shield (just like gradient was before). And I think white would be best.

> Code review symbols usually seem to involve magnifying glasses (...) I'm not sure how to combine that with the idea of security, and dependencies or packages.

Very though bet, but what if we took that magnifying glass with `</>` inside and replaced the three circles with circles like this (with `</>`?). Something like this. I'm not sure how legible it would be (too much detail?), but then it would be kind of perfect - two colors, coming together, looking into dependencies and doing a code review.

Maybe we could make these three lines shaped more like dependency tree too? 90 degree angles kind of things? Maybe not exactly but just more like it? In that case I would also consider  flipping sides (left/right) as dependecy trees usually look like:


```
|
|----
|   |----
--------
```

From left to right.

**Comment by kornelski** [comment]
Some ideas for a logo:

* A box (or a crate) with a stamp of approval

* An owl (cartoon owls can have a shape of a shield)

* Helmet/hard hat

**Comment by kornelski** [comment]
suspicious-owl

**Comment by dpc** [comment]
BTW. At the core `crev` is very generic (WoT + yaml documents) and could be used to review things other than libraries. It was even part of the original plan.

@kornelski This owl looks suspiciously similar to a well known gopher. :D

**Comment by kornelski** [comment]
Few more ideas:

Opening crates to see what's inside:

open2
open1

Crates can be random things:

random-crate

**Comment by dpc** [comment]
Using crates in logo seems very rust-specific. Logos don't have to explain anything. E.g. Most brands use very abstract logos. They help with visual identification, and set a cognitive association - that's why IMO it's more about style, font, colors and "the feel" than trying to explain things.

**Comment by dpc** [comment]
I think we should just roll with this logo. My rule of thumb for landing stuff is - if it is better than it was before, land it. :) . If anyone ever comes us up with a better one, we can always revise. And the current one is ugly, since I picked it up. :D . I kind of like this one, and it seems to have some symbolism behind it, shield, probes, sides coming together. Better than I'd expect for such an immature project. :)

I've spend some time in inkscape playing with it and I think the few final touches would be nice. Seems to me the background in the shape of the shield itself should be included. Then it looks OK on any background. I'm too lame with Inkscape to figure it out myself.

You can optimize the size by joining all objects into paths. Also, I'm not very fond of the tips at the bottom. They look kind of ... heavier than rest of the outline. I've pushed `pr-347-toying-by-dpc` branch with different tips. I was actually looking for different colors, but I'm really bad at picking colors, so I don't like the blue + green that I've left it with.

Anyway, I very much appreciate you @ffranr taking a stab at this.

**Comment by ffranr** [comment]
@dpc I have a few more ideas around this. If you don't mind, could we stall implementing the logo change for a bit? (At least my proposed change, if it's someone else's proposed change then change as you wish of course!)

I also haven't checked out your changes yet. But I will! :)

**Comment by dpc** [comment]
Fine with me. Take your time. But if you lose patience and energy, land the best thing you have.

**Pull request closed without merging**
