### PR TITLE
Id without a URL can be trusted

### LINKED ISSUE #300: Trust Crev Id without a URL
Currently `crev id trust` wants to know a URL for the Id.

> Error: URL not found for Id yadayada; Fetch proofs with `fetch url <url>` first

This means I can't tell others "I'm X98FCpyv5I7z-xv4u-zMWLsFgb_Y0cG7p5xNFHSjbLA add me to crev!" and requires sharing of URL + Id together. It also nudges users towards sharing just the URL, because an Id can be read from a URL.

If crev could create a trust proof without the `url` field, it would make crev Ids more practical for sharing as *the* identity, rather than a secondary thing with *URL* being the identity. 

Related to #298

### PR DESCRIPTION
**Pull request by kornelski**
Fixes #300

On top of #299 to avoid merge conflicts

### CODE REVIEW

**Comment by dpc** [comment]
Relevant parts look OK to me, I guess. We should make sure that if `None` we sensibly back-fill it with a trusted url if possible, particularly next time the trust proof is created. Also, this will be a backward-compat-breaking change - nothing too bad (proof will just get ignored by previous versions), I think.

Let me know when and which PR is ready for landing. You could try just rebasing #299 on top of this one, so we could merge this one first. If it works.

**Comment by kornelski** [comment]
This PR uses functions I've added in the previous one, so a rebase would be messy

**Comment by dpc** [comment]
So do I land this one or first the previous one? And are they ready? :D

**Comment by kornelski** [comment]
#299 should be merged first

**Pull request closed without merging**
